services:
  picker:
    build:
      context: .
      dockerfile: controller.Dockerfile
    container_name: gluetun-picker
    user: "${PUID:-1000}:${PGID:-1000}"
    group_add:
      - "${DOCKER_GID:-985}"
    env_file:
      - ./.env
    command:
      - auto
      - --limit
      - "10"
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
